[theme]
primaryColor = "#10B981"            # verde menta (acentos)
backgroundColor = "#0B1221"         # azul petr√≥leo oscuro
secondaryBackgroundColor = "#111827"
textColor = "#E5E7EB"
font = "sans serif"
